pip install tensorflow==2.10.1
pip install tf_slim
pip install lvis
pip install scipy
pip install --no-deps tensorflowjs
pip install s3fs
pip install Pillow
pip install pycocotools
pip install tensorflow-hub
pip install PyInquirer
pip install h5py
pip install PyYAML
pip install gin-config
pip install tensorflow-addons
pip install tensorflow_io
pip install apache-beam
pip install avro-python3
pip install contextlib2
pip install lxml
pip install pandas
pip install tf-models-official
